name: honua
description: Save the planet

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  introduction_screen: ^1.0.9
  shared_preferences: ^0.5.7+3
  provider: ^4.1.3
  sleek_circular_slider: ^1.1.0
  cached_network_image: ^2.2.0+1
  flutter_local_notifications: ^1.4.4+1
  full_screen_image: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/onboarding/
    - assets/honua.png
    - assets/fonts/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300